@baseUrl = http://localhost:3333/api


POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test",
    "name": "test"

}


### sign in
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "tes12121212t"
}      


### create organization
POST {{baseUrl}}/auth/org
Content-Type: application/json

{
    "name": "test",
    "description": "test"
}